import requests

response = requests.get("https://opentdb.com/api.php", params={"amount":10, "type":"boolean"})
response.raise_for_status()
question_data = response.json()


# question_data = {
#     "response_code": 0,
#     "results": [
#         {"category": "Entertainment: Music",
#          "type": "boolean",
#          "difficulty": "medium",
#          "question": "Rapper Snoop Dogg&#039;s real name is &#039;Cordozar Calvin Broadus, Jr.&#039;.",
#          "correct_answer": "True",
#          "incorrect_answers": ["False"]},
#         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#          "question": "The Mann Co. Store from Team Fortress 2 has the slogan &quot;We hire mercenaries and get in fights&quot;.",
#          "correct_answer": "False", "incorrect_answers": ["True"]},
#         {"category": "History", "type": "boolean", "difficulty": "medium",
#          "question": "The first televised presidential debate was between Jimmy Carter and Gerald Ford.",
#          "correct_answer": "False", "incorrect_answers": ["True"]},
#         {"category": "Geography", "type": "boolean", "difficulty": "medium",
#          "question": "The surface area of Russia is slightly larger than that of the dwarf planet Pluto.",
#          "correct_answer": "True", "incorrect_answers": ["False"]},
#         {"category": "Geography", "type": "boolean", "difficulty": "easy",
#          "question": "The Republic of Malta is the smallest microstate worldwide.", "correct_answer": "False",
#          "incorrect_answers": ["True"]}, {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
#                                           "question": "There aren&#039;t any live-action clones in &quot;Star Wars: Episode III - Revenge of the Sith&quot;.",
#                                           "correct_answer": "True", "incorrect_answers": ["False"]},
#         {"category": "History", "type": "boolean", "difficulty": "easy",
#          "question": "The Spitfire originated from a racing plane.", "correct_answer": "True",
#          "incorrect_answers": ["False"]}, {"category": "History", "type": "boolean", "difficulty": "hard",
#                                            "question": "Joseph Stalin&#039;s real name was Ioseb Bessarionis dze Dzugashvili.",
#                                            "correct_answer": "True", "incorrect_answers": ["False"]},
#         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#          "question": "&quot;Undertale&quot; is an RPG created by Toby Fox and released in 2015.",
#          "correct_answer": "True",
#          "incorrect_answers": ["False"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
#                                            "question": "The sum of all the numbers on a roulette wheel is 666.",
#                                            "correct_answer": "True", "incorrect_answers": ["False"]},
#         {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
#          "question": "There are 86400 seconds in a day.", "correct_answer": "True", "incorrect_answers": ["False"]},
#         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
#          "question": "In the game &quot;Melty Blood Actress Again Current Code&quot;, you can enter Blood Heat mode in Half Moon style.",
#          "correct_answer": "False", "incorrect_answers": ["True"]},
#         {"category": "History", "type": "boolean", "difficulty": "medium",
#          "question": "Brezhnev was the 5th leader of the USSR.", "correct_answer": "True",
#          "incorrect_answers": ["False"]},
#         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#          "question": "Donkey Kong was originally set to be a Popeye arcade game.", "correct_answer": "True",
#          "incorrect_answers": ["False"]},
#         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#          "question": "Niko Bellic is the protagonist of Grand Theft Auto IV.", "correct_answer": "True",
#          "incorrect_answers": ["False"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#                                            "question": "RAM stands for Random Access Memory.", "correct_answer": "True",
#                                            "incorrect_answers": ["False"]},
#         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#          "question": "In Kingdom Hearts the Paopu fruit is said to intertwine the destinies for two people forever.",
#          "correct_answer": "True", "incorrect_answers": ["False"]},
#         {"category": "History", "type": "boolean", "difficulty": "medium",
#          "question": "If you grab the bladed end of a longsword in a specific way, you will not cut yourself.",
#          "correct_answer": "True", "incorrect_answers": ["False"]},
#         {"category": "Science: Mathematics", "type": "boolean", "difficulty": "hard",
#          "question": "If you could fold a piece of paper in half 50 times, its&#039; thickness will be 3\/4th the distance from the Earth to the Sun.",
#          "correct_answer": "True", "incorrect_answers": ["False"]},
#         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#          "question": "Gordon Freeman, the protagonist of &quot;Half-Life&quot;, is said to have once had a ponytail.",
#          "correct_answer": "True", "incorrect_answers": ["False"]},
#         {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
#          "question": "Kissing someone for one minute burns about 2 calories.", "correct_answer": "True",
#          "incorrect_answers": ["False"]},
#         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#          "question": "The PlayStation was originally a joint project between Sega and Sony that was a Sega Genesis with a disc drive.",
#          "correct_answer": "False", "incorrect_answers": ["True"]},
#         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
#          "question": "TF2: The Medic will be credited for an assist if he heals a Spy that successfully saps a building.",
#          "correct_answer": "True", "incorrect_answers": ["False"]},
#         {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
#          "question": "Gosho Aoyama Made This Series: (Detective Conan \/ Case Closed!)", "correct_answer": "True",
#          "incorrect_answers": ["False"]},
#         {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "medium",
#          "question": "The anime Attack on Titan was directed by Tetsur\u014d Araki, the same person who directed the anime Highschool of the Dead.",
#          "correct_answer": "True", "incorrect_answers": ["False"]},
#         {"category": "Entertainment: Comics", "type": "boolean", "difficulty": "medium",
#          "question": "In the webcomic Homestuck, the first character introduced is Dave Strider.",
#          "correct_answer": "False", "incorrect_answers": ["True"]},
#         {"category": "Animals", "type": "boolean", "difficulty": "medium", "question": "The Platypus is a mammal.",
#          "correct_answer": "True", "incorrect_answers": ["False"]},
#         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#          "question": "In the game &quot;Subnautica&quot;, a &quot;Spadefish&quot; will attack you.",
#          "correct_answer": "False", "incorrect_answers": ["True"]},
#         {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
#          "question": "Sean Connery wasn&#039;t in &quot;Indiana Jones and the Kingdom of the Crystal Skull&quot; because he found retirement too enjoyable.",
#          "correct_answer": "True", "incorrect_answers": ["False"]},
#         {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
#          "question": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ",
#          "correct_answer": "True", "incorrect_answers": ["False"]},
#         {"category": "Sports", "type": "boolean", "difficulty": "medium",
#          "question": "Formula E is an auto racing series that uses hybrid electric race cars.",
#          "correct_answer": "False",
#          "incorrect_answers": ["True"]}, {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
#                                           "question": "Bugatti was an Italian car manufacturer.",
#                                           "correct_answer": "False",
#                                           "incorrect_answers": ["True"]},
#         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#          "question": "In &quot;Undertale&quot;, the main character of the game is Sans.", "correct_answer": "False",
#          "incorrect_answers": ["True"]}, {"category": "Sports", "type": "boolean", "difficulty": "easy",
#                                           "question": "In Rugby League, performing a &quot;40-20&quot; is punished by a free kick for the opposing team.",
#                                           "correct_answer": "False", "incorrect_answers": ["True"]},
#         {"category": "Entertainment: Cartoon & Animations", "type": "boolean", "difficulty": "easy",
#          "question": "Waylon Smithers from &quot;The Simpsons&quot; was originally black when he first appeared in the series.",
#          "correct_answer": "True", "incorrect_answers": ["False"]},
#         {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "medium",
#          "question": "&quot;Rich Uncle Pennybags&quot; from the board game &quot;Monopoly&quot; wears a monocle.",
#          "correct_answer": "False", "incorrect_answers": ["True"]},
#         {"category": "Politics", "type": "boolean", "difficulty": "medium",
#          "question": "Helen Clark was the 37th Prime Minister of Australia.", "correct_answer": "False",
#          "incorrect_answers": ["True"]},
#         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
#          "question": "In &quot;Call Of Duty: World At War&quot;, the first appearance of the &quot;PPSH-41&quot; in &quot;Zombies&quot; was in the map &quot;Der Riese&quot;.",
#          "correct_answer": "False", "incorrect_answers": ["True"]},
#         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#          "question": "The game &quot;Pocket Morty&quot; has a Morty called &quot;Pocket Mortys Morty&quot;?",
#          "correct_answer": "True", "incorrect_answers": ["False"]},
#         {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
#          "question": "Pneumonoultramicroscopicsilicovolcanoconiosis is a synonym for the disease known as silicosis.",
#          "correct_answer": "True", "incorrect_answers": ["False"]},
#         {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
#          "question": "Michael Jackson wrote The Simpsons song &quot;Do the Bartman&quot;.", "correct_answer": "False",
#          "incorrect_answers": ["True"]},
#         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
#          "question": "The scrapped Sonic the Hedgehog 2 level &quot;Hidden Palace Zone&quot; was later reused in the iOS port of the game. ",
#          "correct_answer": "True", "incorrect_answers": ["False"]},
#         {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
#          "question": "&quot;Foodfight!&quot; earned less than $80,000 at box office.", "correct_answer": "True",
#          "incorrect_answers": ["False"]}, {"category": "Entertainment: Music", "type": "boolean", "difficulty": "hard",
#                                            "question": "The singer Billie Holiday was also known as &quot;Lady Day&quot;.",
#                                            "correct_answer": "True", "incorrect_answers": ["False"]},
#         {"category": "Entertainment: Cartoon & Animations", "type": "boolean", "difficulty": "medium",
#          "question": "Nutcracker Suite was one of the musical pieces featured in Disney&#039;s 1940&#039;s film Fantasia.",
#          "correct_answer": "True", "incorrect_answers": ["False"]},
#         {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
#          "question": "A Facebook campaign placed Rage Against The Machine&#039;s &quot;Killing in the Name Of&quot; as the UK Christmas Number 1 in 2009.",
#          "correct_answer": "True", "incorrect_answers": ["False"]},
#         {"category": "Politics", "type": "boolean", "difficulty": "medium",
#          "question": "Jeb Bush was elected as Governor of Florida in 2002, starting his political career.",
#          "correct_answer": "False", "incorrect_answers": ["True"]},
#         {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
#          "question": "Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.",
#          "correct_answer": "True", "incorrect_answers": ["False"]},
#         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#          "question": "In the video game &quot;Splatoon&quot;, the playable characters were originally going to be rabbits instead of squids.",
#          "correct_answer": "True", "incorrect_answers": ["False"]},
#         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#          "question": "In Resident Evil 4, the Chicago Typewriter has infinite ammo.", "correct_answer": "True",
#          "incorrect_answers": ["False"]}]}
